### PR TITLE
Feature/advect blob

### PR DESCRIPTION
**Pull request by hbrunie**
Adding some PDE test cases to highlight adaptivity usefulness. 

## Proposed changes
Adding advect blob 1 2 3 and 4. Inspired from David commit on DG-SparseGrid

### Does this introduce a breaking change?
- [X] No

## What systems has this change been tested on?
Cori Haswell and GPU Nvidia V100 and laptop INTEL i5 8th generation

## Todo list
- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [x] Build related changes: Adding pde to ./asgard -a (helper)
- [ ] Documentation content changes: Adding advect_blob PDE description

### CODE REVIEW

**Comment by hbrunie** [comment]
No need for tests based on golden result from matlab. (discussion with @dlg0 )
Only test that the RMSE between simulated and analytical solution does not exceed arbitrary threshold.
What should be this threshold?

**Comment by dlg0** [comment]
something that will allow the test to be fast, so a relative error of 1e-3 or so is fine, running at lev=3, deg=3 or so. Just double check that if you increase lev by 1 that the error goes down by about a factor of (deg+1)

**Comment by hbrunie** [comment]
> something that will allow the test to be fast, so a relative error of 1e-3 or so is fine, running at lev=3, deg=3 or so. Just double check that if you increase lev by 1 that the error goes down by about a factor of (deg+1)

Looking at the tests `pde_tests.cpp` I can not find any test on "equality" between exact and simulated solution.
For every PDEs, the exact solution is compared to the exact golden results from DG-SparseGrid. 
But the C++ simulated solution is never compared to the C++ exact solution.

This is already highlighted in the issue:  #373.

**Comment by dlg0** [comment]
That's something I did not know. We can certainly fix that - although it's not like it is really "wrong", but I'd prefer it to be testing against the C++ generated exact solution. So for your new one, just test against the C++ exact solution.

**Comment by hbrunie** [comment]
There is another PR adding the tests between C++ simulated solution and analytic one (#402 ).
Once the #402  PR is accepted and merged, I will rebase this one #394  on top of it and add the corresponding tests for advect_blob.

**Comment by mkstoyanov** [comment]
Stalled PR, feel free to resubmit based on the latest developments.

**Pull request closed without merging**
