### PR TITLE
WIP: Tackling Issue #82 to use deg+1 in quad_num variables 

### PR DESCRIPTION
**Pull request by Marijhq**
Changing the variables quad_num, quadrature_num, & stepping for dim.get_degree()+1

### CODE REVIEW

**Comment by grahamlopez** [comment]
okay to test

**Comment by grahamlopez** [comment]
There is an intermittent failure in `apply_fmwt()` here. To reproduce:
```
cmake -DCMAKE_CXX_COMPILER=clang++
make -j
for bob in $(seq 1 20) ; do ./basis-tests ; done
```
@tyounkin thoughts?

**Comment by tyounkin** [comment]
@grahamlopez @Marijhq I am taking a look at this now. I'll try to have an update soon.

**Comment by bmcdanie** [comment]
implemented in #206

**Pull request closed without merging**
