### PR TITLE
added num threads and blocks as compile options

### PR DESCRIPTION
**Pull request by mkstoyanov**
* added num threads and blocks as compile options

### CODE REVIEW

**Comment by mkstoyanov** [comment]
I removed hard-coded Volta architecture and now things are open to the user. However, CMake tends to default to the lowers architecture available, which is currently Maxwell (no good).

@quantumsteve 

If the CI containers don't specify environment variable `CUDAARCH` we must either specify that, or specify `CMAKE_CUDA_ARCHITECTURES` or update CMake to 3.24 (or newer) which has the ability to auto-detect the existing GPUs.

**Comment by quantumsteve** [comment]
The GPU containers have CMake 3.26 from the Kitware PPA.
________________________________
From: Miroslav Stoyanov ***@***.***>
Sent: Wednesday, April 26, 2023 12:57 PM
To: project-asgard/asgard ***@***.***>
Cc: Hahn, Steven ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [project-asgard/asgard] added num threads and blocks as compile options (PR #536)


I removed hard-coded Volta architecture and now things are open to the user. However, CMake tends to default to the lowers architecture available, which is currently Maxwell (no good).

@quantumsteve<https://github.com/quantumsteve>

If the CI containers don't specify environment variable CUDAARCH we must either specify that, or specify CMAKE_CUDA_ARCHITECTURES or update CMake to 3.24 (or newer) which has the ability to auto-detect the existing GPUs.

**Review by quantumsteve — APPROVED** [review]
```
$ grep "native" compile_commands.json 
  "command": "/usr/local/cuda-12.1/bin/nvcc -forward-unknown-to-host-compiler -DUSE_GPU --options-file CMakeFiles/asgard_obj.dir/includes_CUDA.rsp -g -std=c++17 -arch=native -g -lineinfo --ptxas-options=-O3 --compiler-options -fPIC --keep-device-functions -x cu -c /home/svh/Documents/asgard/src/device/kronmult_cuda.cpp -o CMakeFiles/asgard_obj.dir/src/device/kronmult_cuda.cpp.o",
  "command": "/usr/local/cuda-12.1/bin/nvcc -forward-unknown-to-host-compiler -DUSE_GPU --options-file CMakeFiles/asgard_obj.dir/includes_CUDA.rsp -g -std=c++17 -arch=native -g -lineinfo --ptxas-options=-O3 --compiler-options -fPIC --keep-device-functions -x cu -c /home/svh/Documents/asgard/src/device/asgard_kronmult.cpp -o CMakeFiles/asgard_obj.dir/src/device/asgard_kronmult.cpp.o",
```

**Comment by mkstoyanov** [comment]
Tests are passing now. With CMake 3.24 it will default to `native` mode which is good. With older CMake you will need to either specify `CMAKE_CUDA_ARCHITECTURES` or environment variable `CUDAARCH` (as defined by the CMake documentation).

**Pull request merged**
