### PR TITLE
handle case when non-identity and no flux term

### PR DESCRIPTION
**Pull request by mkstoyanov**
@stefan-schnake

The flux term should always be at position `0` in the `active_terms` as this is the one that doesn't get split into upper/lower part. Active term `0` does not require completeness of the hierarchy, the rest of directions can be given in any order.

This fixes the case when we have a term that is a mass term (no flux) but is not identity. We should also double-check the logic in `get_flux_direction()`.

### CODE REVIEW

**Review by stefan-schnake — COMMENTED** [review]
If were reviewing this now:
`pt.coeff_type == coefficient_type::penalty` needs to be added to L1199.

**Review by stefan-schnake — COMMENTED** [review]
This looks fine.  The bug would show itself if we had a term of all masses, but we don't have a PDE that does that (yet).  Maybe we should have a test for $u_t + u = \Delta u$.

**Comment by mkstoyanov** [comment]
@stefan-schnake How does it look now?

**Comment by mkstoyanov** [comment]
> This looks fine. The bug would show itself if we had a term of all masses, but we don't have a PDE that does that (yet). Maybe we should have a test for ut+u=Δu.

True enough, we are missing tests for lots of corner cases. Part of the problem is the clumsy way of adding new PDEs and the need to integrate them into the library as opposed to just having them externally defined.

**Comment by stefan-schnake** [comment]
BGK includes a mass term, so we'll just wait for that.

**Review by stefan-schnake — APPROVED** [review]

**Pull request merged**
