### PR TITLE
Change unordered_set to unordered_map to fix compiling error on Apple…

### PR DESCRIPTION
**Pull request by cianciosa**
… Clang.

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This corrects a header include issue that was triggered on apple clang using the libc++ standard library.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

macOS X 10.15.7

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Comment by cianciosa** [comment]
Github issue https://github.com/project-asgard/asgard/issues/387

**Comment by quantumsteve** [comment]
@cianciosa Would you please add another empty commit to restart CI? I tried adding you to all of the whitelists.

**Comment by cianciosa** [comment]
@quantumsteve It looks like every test except asgard-unit-io ran.

**Comment by quantumsteve** [comment]
> @quantumsteve It looks like every test except asgard-unit-io ran.

Oops, forgot to add your account id there. Would you try again?

**Comment by quantumsteve** [comment]
@ckendrick @dlg0 Do you see anything in the `asgard-unit-io` whitelist that would stop it from starting up?

**Comment by dlg0** [comment]
I just issued a new PR to test it, and it seems to start for me. For whom is it not starting? If it is only @cianciosa, perhaps he can try issuing another dummy commit now to test?
________________________________
From: Steven Hahn ***@***.***>
Sent: Wednesday, April 7, 2021 3:27 PM
To: project-asgard/asgard ***@***.***>
Cc: Green, David ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [project-asgard/asgard] Change unordered_set to unordered_map to fix compiling error on Apple… (#388)


@ckendrick<https://github.com/ckendrick> @dlg0<https://github.com/dlg0> Do you see anything in the asgard-unit-io whitelist that would stop it from starting up?

**Comment by cianciosa** [comment]
> I just issued a new PR to test it, and it seems to start for me. For whom is it not starting? If it is only @cianciosa, perhaps he can try issuing another dummy commit now to test?
> […](#)

Still having the same problem.

**Comment by dlg0** [comment]
There seems to be a disconnect between the reporting to github and the AWS builds starting. They all seemed to start (and complete I think - although I will try again now), but then only some are reported back to github. Please hold as I try again ...

**Comment by quantumsteve** [comment]
I Received an email to [reset any personal access tokens and OAuth tokens you have](
https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/).

Might be worth trying for the two tests that aren't starting 🤔

**Comment by cianciosa** [comment]
Still not running. Where are the access restrictions configured? I'm having trouble locating them. Also I was wondering if it might be some issue in the GitHub webhook. I see the unit-io has a different webhook url than unit-clang. So maybe it's something in the webhook configuration. Unfortunately anytime I try to access those, I get a 404 not found error. Which is probably due to not having write access to this repo.

**Review by dlg0 — APPROVED** [review]
Looks fine.

**Pull request merged**
