### PR TITLE
Feature/highfive

### PR DESCRIPTION
**Pull request by grahamlopez**

### CODE REVIEW

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
@dlg0 let's give it another shot now; ready for review

**Comment by grahamlopez** [comment]
some updated behavior:
1) the `#ifdefs` are controlled via cmake through the `build_config.hpp.in` file. this is where we will consolidate the communications between build-time configuration via cmake and the code.
2) if `-DASGARD_IO_HIGHFIVE=1` is requested, then cmake will download highfive if necessary, and will build hdf5 if necessary
3) cmake will try to find hdf5 and use it from the system
4) cmake will take a custom path from the user for the location of hdf5 via `-DASGARD_HDF5_PATH`
5) the user can force building/using their own hdf5 in contrib via `-DASGARD_BUILD_HDF5` (in case an automatically found one on the system is broken)

**Comment by dlg0** [comment]
[Just copying this over from code.ornl.gov]
Some notes on the spack install of `HighFive` ... because if we end up keeping highfive, we may end up using spack to build it (or put it into the container for the CI).
*  `spack install hdf5~mpi`
*  `spack edit highfive` to add the git and master version options. 
*  `spack install highfive@master~mpi ^hdf5 /${hdf5hash}` to build against a specific version of hdf5 (the one without MPI)
*  Use `spack find -l` to get the ${hdf5hash}

**Comment by grahamlopez** [comment]
> [Just copying this over from code.ornl.gov]
> Some notes on the spack install of `HighFive` ... because if we end up keeping highfive, we may end up using spack to build it (or put it into the container for the CI).
> 
>     * `spack install hdf5~mpi`
> 
>     * `spack edit highfive` to add the git and master version options.
> 
>     * `spack install highfive@master~mpi ^hdf5 /${hdf5hash}` to build against a specific version of hdf5 (the one without MPI)
> 
>     * Use `spack find -l` to get the ${hdf5hash}

Good to have for reference. The current CMake implementation will just grab HighFive from github for you automatically. There shouldn't be any need for anyone to ever install by hand.

**Comment by dlg0** [comment]
> spack install highfive@master~mpi ^hdf5 /${hdf5hash

Yeah, I'm going to try all of the approaches.

**Comment by grahamlopez** [comment]
test this please

**Pull request merged**
