### PR TITLE
fix osx issue with reading floats

### PR DESCRIPTION
**Pull request by mkstoyanov**
This should fix the issue with float precision in Mac.

Basically, the `>>` fails to read the double data as floats.

### CODE REVIEW

**Comment by quantumsteve** [comment]
What do you think about creating a minimal reproducible example for libc++?

**Review by quantumsteve — APPROVED** [review]
Let's get this into develop and rebase #738.

**Comment by mkstoyanov** [comment]
@quantumsteve 

I'm overriding the test requirement, we have too many tests now, we should disable the duplicates from AWS.

**Comment by mkstoyanov** [comment]
> What do you think about creating a minimal reproducible example for libc++?

We can do that but I also want to check what the standard says too.

**Comment by quantumsteve** [comment]
> @quantumsteve
> 
> I'm overriding the test requirement, we have too many tests now, we should disable the duplicates from A

I've disabled the duplicate tests from running on pull requests but haven't figured out why GitHub is still waiting for results from them.

**Comment by mkstoyanov** [comment]
> > @quantumsteve
> > I'm overriding the test requirement, we have too many tests now, we should disable the duplicates from A
> 
> I've disabled the duplicate tests from running on pull requests but haven't figured out why GitHub is still waiting for results from them.

So we're waiting on tests that will never run.

Must be something in the hooks, there must be something in the github setup that is calling AWS. Maybe something in the AWS has to be force-updated ... ugh!

**Pull request merged**
