### PR TITLE
Full global kron

### PR DESCRIPTION
**Pull request by mkstoyanov**
* moved all kronmult operations to global mode
* removed the need for padding (handled the fluxes right)
* blocked all old code behind ifdef, can still be enabled
* large clang cleanup

### CODE REVIEW

**Comment by stefan-schnake** [comment]
> * moved all kronmult operations to global mode
> * removed the need for padding (handled the fluxes right)
> * blocked all old code behind ifdef, can still be enabled
> * large clang cleanup

Can I start checking for correctness on the global kronmult?

**Comment by mkstoyanov** [comment]
@stefan-schnake Added padding for the volume hierarchy. When you get a chance, push it through another set of stress tests.

Merry Christmas!

**Review by stefan-schnake — APPROVED** [review]
`./asgard -p relaxation_1x3v -d 3 -x -t 5e-4 -l "0 7 7 7" -n 10 --inner_it 100 --tol 1e-14 --wave_freq 1 --kron-mode sparse -m 9` gives errors from 2e-14 to 3e-14 when compared to develop.

`./asgard -p two_stream -d 3 -x -t 0.0015625 -l "7 7" -n 100 --wave_freq 1 --kron-mode sparse -m 7 --adapt --thresh 1e-3` gives errors near machine epsilon when compared to develop.  This is when the mesh is and is not parent complete.

**Comment by mkstoyanov** [comment]
> `./asgard -p relaxation_1x3v -d 3 -x -t 5e-4 -l "0 7 7 7" -n 10 --inner_it 100 --tol 1e-14 --wave_freq 1 --kron-mode sparse -m 9` gives errors from 2e-14 to 3e-14 when compared to develop.
> 
> `./asgard -p two_stream -d 3 -x -t 0.0015625 -l "7 7" -n 100 --wave_freq 1 --kron-mode sparse -m 7 --adapt --thresh 1e-3` gives errors near machine epsilon when compared to develop. This is when the mesh is and is not parent complete.

Great! That's what we wanted!

@quantumsteve You can review the code if you want.

**Comment by quantumsteve** [comment]
> @quantumsteve You can review the code if you want.

Go ahead with @stefan-schnake's review. I was out last week.

**Pull request merged**
