### PR TITLE
better permutations, generalized and without recursion

### PR DESCRIPTION
**Pull request by mkstoyanov**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Refactoring of the permutations algorithms to remove the recursions and the extraneous helper methods.
* there is one main algorithm for selecting multi-indexes based on a lower-set criteria
* algorithm for generating full/dense grids of multi-indexes
* few helpers to move data into the appropriate matrix data structures and to handle special cases of ordering

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [x] documentation has been added (if appropriate)

### CODE REVIEW

**Comment by quantumsteve** [comment]
```
[Container] 2022/09/25 23:20:41 Running command bash -c "diff  -u <(cat src/*pp) <(clang-format-12 src/*pp)"
--- /dev/fd/63  2022-09-25 23:20:41.948900821 +0000
+++ /dev/fd/62  2022-09-25 23:20:41.948900821 +0000
@@ -17042,7 +17042,6 @@
 
 namespace permutations
 {
-
 // Given the number of dimensions and a limit, produce n-tuples (n ==
 // 'num_dims') whose elements are non-negative and their sum <= 'limit'. Each
 // tuple becomes a row of the output matrix
@@ -17249,7 +17248,6 @@
 
 namespace permutations
 {
-
 /*!
  * \ingroup permuts
  * \brief Generates the list of multi-indexes that satisfy a general selection

[Container] 2022/09/25 23:20:42 Command did not exit successfully bash -c "diff  -u <(cat src/*pp) <(clang-format-12 src/*pp)" exit status 1
```

**Comment by mkstoyanov** [comment]
Yeah, this is wrong on couple of levels
* I cannot see the error messages, external contributors will have the same problem. Can we make the CI logs public?
* The issue appears on `clang-format-12`, it did not appear when I was using `clang-format-14`. We should document which version we expect.
* Offloading formatting to an automated tool sounds like a good idea, but small discrepancies between versions can cause a mess. How long do we stay on 12 and how many changes do we have to make to the code to keep up?

Something to discuss over the long run.

**Comment by quantumsteve** [comment]
> Yeah, this is wrong on couple of levels
> 
> * I cannot see the error messages, external contributors will have the same problem. Can we make the CI logs public?

I enabled public access on the `asgard-format-clangformat` check. Would you please check if it works for you?

> * The issue appears on `clang-format-12`, it did not appear when I was using `clang-format-14`. We should document which version we expect.

We chose clang-format-12 because it's available on both Ubuntu 20.04 and 22.04 without adding a PPA or building from 
source. Would be wise to update the developer documentation and request template.

> * Offloading formatting to an automated tool sounds like a good idea, but small discrepancies between versions can cause a mess. How long do we stay on 12 and how many changes do we have to make to the code to keep up?
> 
We updated from clang-format-7 to clang-format-12 this summer because it would take extra effort to get the former on Ubuntu 22.04. 

> Something to discuss over the long run.

:+1:

**Comment by mkstoyanov** [comment]
> I enabled public access on the `asgard-format-clangformat` check. Would you please check if it works for you?

When I click on the details, it takes me to the Amazon AWS sing in page.

**Comment by quantumsteve** [comment]
> When I click on the details, it takes me to the Amazon AWS sing in page.

Think I have it working in PR #438 and #439 :crossed_fingers:

**Comment by mkstoyanov** [comment]
@quantumsteve @ckendrick I rebased the branch, but I guess that reset the review approvals.

**Review by ckendrick — APPROVED** [review]

**Pull request merged**
