### PR TITLE
Adjusts kronmult CUDA launch configuration

### PR DESCRIPTION
**Pull request by ckendrick**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This adjusts the kernel launch configurations when calling kronmult to better utilize the GPU.
Running the two-stream level 7 full grid saw the average kronmult time go from 379ms to 233ms. A full IMEX time step went from about 21 seconds to 13.8 seconds.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04, CUDA 11.5, RTX 3080Ti

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Comment by quantumsteve** [comment]
I'm not seeing a significant improvement (probably a different input on my end). Ideas?

time ./asgard -p two_stream -d 3 -l "7 7" -t 1.5625e-3 -f -x -n 100 -m 7
fix_kronmult_launch:
real	1m13.275s
user	6m32.582s
sys	0m38.814s

develop:
real	1m13.178s
user	6m24.519s
sys	0m39.491s

**Comment by ckendrick** [comment]
> I'm not seeing a significant improvement (probably a different input on my end). Ideas?
> 
> time ./asgard -p two_stream -d 3 -l "7 7" -t 1.5625e-3 -f -x -n 100 -m 7 fix_kronmult_launch: real 1m13.275s user 6m32.582s sys 0m38.814s
> 
> develop: real 1m13.178s user 6m24.519s sys 0m39.491s

These timings seem very fast. I have run into an issue where (when built with `Release`) this level 7 run over-allocates the device memory. The hash table becomes 0's and all the kernels finish extremely fast. Building with `Debug` should show an error at the allocation.

The timings I posted in the PR were run with the `--memory 8192` option for a card with 12GB.

**Comment by quantumsteve** [comment]
> The timings I posted in the PR were run with the `--memory 8192` option for a card with 12GB.

The timings above are from the 4GB card in my laptop. It's running a lot slower (correctly?) on the 16GB card in my workstation.

**Comment by quantumsteve** [comment]
develop
```
performance report, all times in ms...

explicit_1 - avg: 8559.7281 min: 8550.599 max: 8572.844 med: 8559.0380  calls: 100
explicit_2 - avg: 8699.8174 min: 8677.872 max: 8761.616 med: 8699.6815  calls: 100
gen_coefficients - avg: 123.3107 min: 114.847 max: 202.244 med: 118.3980  calls: 401
imex_time_advance - avg: 18718.2805 min: 18623.350 max: 19007.828 med: 18704.7625  calls: 100
implicit_1 - avg: 222.6811 min: 178.319 max: 338.695 med: 218.1275  calls: 100
implicit_2_coeff - avg: 124.6002 min: 116.133 max: 193.192 med: 118.7080  calls: 100
implicit_2_mom - avg: 98.3746 min: 24.682 max: 190.869 med: 87.9315  calls: 100
interp1 - avg: 0.0000 min: 0.000 max: 0.048 med: 0.0000  calls: 1020000
kronmult - avg: 451.6254 min: 450.669 max: 462.071 med: 451.5510  avg gflops: 16.048214 calls: 3200
kronmult_build - avg: 60.6023 min: 59.443 max: 61.739 med: 60.5975  calls: 3200
kronmult_setup - avg: 8556.8290 min: 8544.814 max: 8572.132 med: 8556.1500  calls: 200
kronmult_stage - avg: 21.6335 min: 21.545 max: 23.497 med: 21.6010  calls: 3200
poisson_solver - avg: 0.0244 min: 0.021 max: 0.111 med: 0.0230  calls: 200
poisson_update - avg: 26.5563 min: 6.879 max: 63.217 med: 27.3155  calls: 200
wavelet_to_realspace - avg: 689.8584 min: 1.239 max: 6706.008 med: 1.3860  calls: 901
```
ckendrick:fix_kronmult_launch

```
performance report, all times in ms...

explicit_1 - avg: 26164.7727 min: 26153.824 max: 26187.093 med: 26165.2570  calls: 100
explicit_2 - avg: 26301.0853 min: 26276.817 max: 26344.232 med: 26301.0175  calls: 100
gen_coefficients - avg: 118.5471 min: 111.772 max: 187.452 med: 115.3840  calls: 401
imex_time_advance - avg: 53917.7258 min: 53874.443 max: 54056.015 med: 53910.8180  calls: 100
implicit_1 - avg: 223.0605 min: 191.236 max: 294.459 med: 213.7340  calls: 100
implicit_2_coeff - avg: 120.5524 min: 113.216 max: 133.013 med: 123.5980  calls: 100
implicit_2_mom - avg: 93.1552 min: 31.627 max: 169.544 med: 94.1900  calls: 100
interp1 - avg: 0.0000 min: 0.000 max: 0.035 med: 0.0000  calls: 1020000
kronmult - avg: 1551.9699 min: 1548.108 max: 1562.597 med: 1551.8550  avg gflops: 4.670042 calls: 3200
kronmult_build - avg: 60.5758 min: 59.497 max: 63.428 med: 60.5655  calls: 3200
kronmult_setup - avg: 26161.8579 min: 26146.161 max: 26185.237 med: 26161.7660  calls: 200
kronmult_stage - avg: 21.6727 min: 21.590 max: 23.628 med: 21.6030  calls: 3200
poisson_solver - avg: 0.0232 min: 0.020 max: 0.081 med: 0.0220  calls: 200
poisson_update - avg: 26.7264 min: 6.791 max: 49.239 med: 28.3945  calls: 200
wavelet_to_realspace - avg: 725.7986 min: 1.203 max: 6700.642 med: 1.3380  calls: 901
```

**Comment by quantumsteve** [comment]
time ./asgard -p two_stream -d 3 -l "7 7" -t 1.5625e-3 -f -x -n 10 -m 7

fusiont5 - develop
```
performance report, all times in ms...

explicit_1 - avg: 7.4885 min: 1.885 max: 56.557 med: 1.9205  calls: 10 
explicit_2 - avg: 208.2206 min: 197.700 max: 223.815 med: 206.2545  calls: 10 
gen_coefficients - avg: 194.5102 min: 174.566 max: 562.603 med: 183.7380  calls: 41 
imex_time_advance - avg: 3243.1560 min: 1909.255 max: 9777.843 med: 2276.9620  calls: 10 
implicit_1 - avg: 584.0219 min: 243.651 max: 2425.867 med: 250.6855  calls: 10 
implicit_2_coeff - avg: 224.0147 min: 174.573 max: 562.608 med: 188.0660  calls: 10 
implicit_2_mom - avg: 865.1939 min: 65.487 max: 5754.705 med: 71.3425  calls: 10 
interp1 - avg: 0.0004 min: 0.000 max: 0.015 med: 0.0000  calls: 102000 
kronmult - avg: 0.0012 min: 0.000 max: 0.022 med: 0.0010  avg gflops: inf calls: 320 
kronmult_build - avg: 0.0825 min: 0.000 max: 25.993 med: 0.0010  calls: 320 
kronmult_setup - avg: 4.1474 min: 1.362 max: 55.932 med: 1.3980  calls: 20 
kronmult_stage - avg: 0.0249 min: 0.000 max: 7.439 med: 0.0010  calls: 320 
poisson_solver - avg: 0.0348 min: 0.028 max: 0.045 med: 0.0360  calls: 20 
poisson_update - avg: 92.0521 min: 19.021 max: 785.023 med: 25.2300  calls: 20 
wavelet_to_realspace - avg: 1032.6860 min: 3.445 max: 9410.977 med: 4.0380  calls: 91

real	2m17.604s
user	83m4.850s
sys	8m51.700s
```
fusiont5 - fix_kronmult_launch
```
performance report, all times in ms...

explicit_1 - avg: 7.7764 min: 1.880 max: 59.515 med: 1.9345  calls: 10 
explicit_2 - avg: 429.8536 min: 206.610 max: 2374.789 med: 211.0720  calls: 10 
gen_coefficients - avg: 231.6607 min: 178.404 max: 609.389 med: 192.1520  calls: 41 
imex_time_advance - avg: 3935.0076 min: 1962.269 max: 11224.566 med: 2924.1625  calls: 10 
implicit_1 - avg: 680.6080 min: 252.614 max: 2452.828 med: 322.9925  calls: 10 
implicit_2_coeff - avg: 188.2172 min: 178.411 max: 221.252 med: 181.7885  calls: 10 
implicit_2_mom - avg: 1264.9385 min: 72.080 max: 4759.961 med: 153.9705  calls: 10 
interp1 - avg: 0.0004 min: 0.000 max: 0.046 med: 0.0000  calls: 102000 
kronmult - avg: 0.0012 min: 0.000 max: 0.051 med: 0.0010  avg gflops: inf calls: 320 
kronmult_build - avg: 0.0873 min: 0.000 max: 27.532 med: 0.0010  calls: 320 
kronmult_setup - avg: 4.1913 min: 1.371 max: 57.085 med: 1.3975  calls: 20 
kronmult_stage - avg: 0.0250 min: 0.000 max: 7.441 med: 0.0010  calls: 320 
poisson_solver - avg: 0.0338 min: 0.025 max: 0.044 med: 0.0325  calls: 20 
poisson_update - avg: 161.6634 min: 19.354 max: 2167.930 med: 26.4515  calls: 20 
wavelet_to_realspace - avg: 1129.0732 min: 3.745 max: 13251.139 med: 4.2490  calls: 91 

real	2m35.957s
user	92m27.533s
sys	13m48.681s
```

**Review by mkstoyanov — APPROVED** [review]

**Pull request merged**
