### PR TITLE
Refactor/no level 1 (depends on #187)

### LINKED ISSUE #89: change asserts to not allow level 1
ASGarD
    asgardasgard
    Issues
    #89

Open
Opened 6 days ago by Graham Lopez
Close issue
New issue
change asserts to not allow level 1
Related issues
0

Graham Lopez @bgl added bug label 6 days ago
Graham Lopez
Graham Lopez @bgl · 6 days ago
Owner

also need the appropriate check for the cli input option

### PR DESCRIPTION
**Pull request by bmcdanie**
closes #89 .

### CODE REVIEW

**Comment by grahamlopez** [comment]
some others I wonder about. please double check:
- basis.cpp:368
- basis.cpp:436 (need assert?)
- connectivity_tests.cpp:33
- connectivity.cpp:13,16,26
- element_table_tests.cpp:14
- element_table:20,92
- pde_base.hpp:92,366,394
- transformations.hpp:50

**Comment by bmcdanie** [comment]
checked all. I think all are correct (except I did add that assert). sometimes I assert `level >=0` when level is used as an index; in all places where we assert on num_levels, I think, I've got it right.

I did add the assert you mentioned - good catch.

**Comment by bmcdanie** [comment]
disregard previous comment...there's somehow a `refactor/no_level1` and `refactor/no_level_1` branch. applying fixes.

**Comment by bmcdanie** [comment]
and `fix/no_level_1`. nice.

**Comment by grahamlopez** [comment]
On Mon, Dec 09, 2019 at 11:17:37AM -0800, Tyler McDaniel wrote:
>disregard previous comment...there's somehow a `refactor/no_level1` and `refactor/no_level_1` branch. applying fixes.

So you're saying there is a problem because someone somewhere didn't follow
naming conventions? :D

**Comment by bmcdanie** [comment]
I had a feeling you'd say that - guilty as charged

**Pull request merged**
