### PR TITLE
fix the test for identity

### PR DESCRIPTION
**Pull request by mkstoyanov**
Fix bug in the way we check if a matrix is identity when using non-Cartesian coordinates.

### CODE REVIEW

**Review by stefan-schnake — DISMISSED** [review]

**Comment by quantumsteve** [comment]
I changed `ctest` to `ctest --output-on-failure` in the AWS buildscript for asgard-unit-io. @mkstoyanov Would you push an empty commit?

**Comment by quantumsteve** [comment]
```
io-tests is a Catch2 v3.1.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
highfive interface to HDF5 - double
  check it writes the correct file
-------------------------------------------------------------------------------
/codebuild/output/src1627854762/src/github.com/project-asgard/asgard/src/io_tests.cpp:10
...............................................................................

/codebuild/output/src1627854762/src/github.com/project-asgard/asgard/src/io_tests.cpp:10: FAILED:
due to unexpected exception with message:
  Impossible to write buffer with dimensions n = 1into dataset with dimensions
  [ 1, 5].

-------------------------------------------------------------------------------
highfive interface to HDF5 - float
  check it writes the correct file
-------------------------------------------------------------------------------
/codebuild/output/src1627854762/src/github.com/project-asgard/asgard/src/io_tests.cpp:10
...............................................................................

/codebuild/output/src1627854762/src/github.com/project-asgard/asgard/src/io_tests.cpp:10: FAILED:
due to unexpected exception with message:
  Impossible to write buffer with dimensions n = 1into dataset with dimensions
  [ 1, 5].

-------------------------------------------------------------------------------
highfive interface to HDF5 - int
  check it writes the correct file
-------------------------------------------------------------------------------
/codebuild/output/src1627854762/src/github.com/project-asgard/asgard/src/io_tests.cpp:10
...............................................................................

/codebuild/output/src1627854762/src/github.com/project-asgard/asgard/src/io_tests.cpp:10: FAILED:
due to unexpected exception with message:
  Impossible to write buffer with dimensions n = 1into dataset with dimensions
  [ 1, 5].

===============================================================================
test cases: 3 | 3 failed
assertions: 3 | 3 failed



97% tests passed, 1 tests failed out of 29

Total Test time (real) =  84.11 sec
```

**Comment by mkstoyanov** [comment]
@quantumsteve Is this due to an update in HDF5 standard? I can't reproduce locally and I don't understand the error message. The code appends a vector to the existing dataset but I'm not familiar with the syntax.

https://github.com/project-asgard/asgard/blob/8c74b7b37c343fbb26b6abd9ef8ba8ea95913268/src/io.hpp#L84

Also, this code is completely independent from the other changes.

**Comment by quantumsteve** [comment]
I also can't reproduce on my machine. I'm currently building `develop` on AWS CodeBuild to see verify the same issue is present there.

**Comment by quantumsteve** [comment]
asgard-unit-io has the same failure on `develop`. Will address in another PR.

**Review by quantumsteve — APPROVED** [review]

**Pull request merged**
