### PR TITLE
BiCGStab solver

### PR DESCRIPTION
**Pull request by quantumsteve**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This adds a BiCGStab solver option for implicit timestepping.

Code follows [iml++](https://math.nist.gov/iml++/bicgstab.h.txt) with minimal changes necessary to utilize fk::vector and matrix-free GMEV. I haven't tried making this work on the GPU.

I'm currently reusing gmres parameters `--tol` and `--outer_it` for tolerance and max iterations. We may want to rename them.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Comment by stefan-schnake** [comment]
Is there a reason BICG isnt in solver.cpp?

**Comment by quantumsteve** [comment]
> Is there a reason BICG isnt in solver.cpp?

In general more, smaller files is easier to understand than few, larger files. That said, there is some common code for the preconditioners that shouldn't be duplicated like I did in this draft.

**Comment by quantumsteve** [comment]
@stefan-schnake Would you please check if BiCGStab is working better with the LB operator in spherical coordinates?

**Comment by quantumsteve** [comment]
@stefan-schnake The CUDA build is working on andremarie. Not sure why I'm getting slightly different results on my laptop (CUDA 12.1 vs 12.5?)

**Comment by mkstoyanov** [comment]
> @stefan-schnake The CUDA build is working on andremarie. Not sure why I'm getting slightly different results on my laptop (CUDA 12.1 vs 12.5?)

I wonder if the issue persists if you disable the preconditioner (of if you are using a preconditioner in the method at all). At least it's one moving part that we can take out of the equation.

A quick and dirty way to disable the preconditioner is to add
```
std::fill(pc.begin(), pc.end(), precision{1});
```
At the very bottom of `build_preconditioner()` in `asgard_kronmult_matrix.hpp`

**Comment by mkstoyanov** [comment]
Did some Kronmult testing and Global kron is messed up on CUDA 12.4 and 12.5. I suspect a cuSparse issue either in API or a bug. I will do some more testing but meanwhile I suggest we revert the CI back to 12.3 and keep moving with the BiCG and the other PRs. If we wait for the CUDA diagnosis we will delay progress on the other fronts by too much.

PS: Tested on a code unrelated to ASGarD and got the same issue ...

**Comment by quantumsteve** [comment]
I can disable `us-east-1 (asgard-unit-cuda)` from the CI. `us-east-2 (asgard-unit-cuda-gxx)` is unchanged (CUDA 11.8).

**Review by mkstoyanov — DISMISSED** [review]

**Comment by quantumsteve** [comment]
Screenshot from 2024-06-24 22-39-08

Old bug where only the solver string and not the enum were set (enum still set to "direct")  prevented any of the "scalapack" solver tests from running. Disabling the scalapack time-advance-tests for now.

**Pull request merged**
