### PR TITLE
fix bug with uninitialized data

### PR DESCRIPTION
**Pull request by mkstoyanov**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

If initializing a vector from an empty matrix, the `data_` will be deleted before initialization.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?
Ubuntu Linux (gcc)

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Review by quantumsteve — CHANGES_REQUESTED** [review]
Thank you for the bug report and PR. Please add a test to [src/tensor_test.cpp](https://github.com/project-asgard/asgard/blob/develop/src/tensors_tests.cpp) that copies from a empty matrix.

**Comment by mkstoyanov** [comment]
Added the unit test.

**Review by quantumsteve — APPROVED** [review]

**Comment by quantumsteve** [comment]
@mkstoyanov Please rebase to bring this branch up-to-date with develop.

**Comment by mkstoyanov** [comment]
Rebased!

**Comment by quantumsteve** [comment]
I forgot to add you to the AWS whitelist :facepalm: Doing that now.

**Comment by mkstoyanov** [comment]
I was wondering why it takes so long :)

**Pull request merged**
