### PR TITLE
Adapt l2 norm

### LINKED ISSUE #648: $L^2$ Coefficient Adaptivity
The current code uses $L^\infty$ adaptivity to determine whether to coarsen/refine.    We should try some tests with $L^2$ to see if we can achieve sparser solutions with similar accuracy.  Lines [267-268](https://github.com/project-asgard/asgard/blob/develop/src/adapt.cpp#L267-L268), [280-281](https://github.com/project-asgard/asgard/blob/develop/src/adapt.cpp#L280-L281), [295-296](https://github.com/project-asgard/asgard/blob/develop/src/adapt.cpp#L295-L296), and [310-311](https://github.com/project-asgard/asgard/blob/develop/src/adapt.cpp#L310-L311) of `adapt.cpp` need to be changed to an $L^2$ norm than an $L^\infty$ norm.

We should test on `two_stream` and `relaxation_1x2v` to see the benefits vs $L^\infty$ adaptivity.  Here's the apprprioate commands:

`two_stream`.  I have data for thresholds of `1e-4` and `1e-6` and FG that I can send you for $L^\infty$.
```
./asgard -p two_stream -l "7 7" -m 7 -d 3 -t 0.0015625 -n 28800 -x --kron-mode sparse --adapt --thresh 1e-6
```

`relaxation_1x2v`. 
```
./asgard -p relaxation_1x2v -l "0 7 7" -m 7 -d 3 -t 5e-4 -n 40 -x --kron-mode sparse --max_adapt_levels "0 7 7" --adapt --thresh 1e-6
```

Try to tune the threshold such that the DOFs such that $L^infty$ and $L^2$ strategies are similar.

### PR DESCRIPTION
**Pull request by quantumsteve**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This adds the command-line option `--l_inf` to use the L\infty instead of the L2 adaptivity to determine whether to coarsen/refine.

This fixed #648 

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [x] Yes
- [] No

Switched default from L\infty to L2.

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Comment by mkstoyanov** [comment]
@stefan-schnake How do we want to have this? I believe we want the opposite, where L-2 is the default and L-infty is the option. What do you think?

**Comment by stefan-schnake** [comment]
> @stefan-schnake How do we want to have this? I believe we want the opposite, where L-2 is the default and L-infty is the option. What do you think?

I would prefer $L^2$ as the default over $L^\infty$, but that probably comes with changing multiple tests.

**Comment by stefan-schnake** [comment]
Also `--l_inf` looks way better than `--l_two`

**Comment by mkstoyanov** [comment]
@quantumsteve when I made the change to the testing and the way the defaults are set, I think it became easy to set a new default, e.g., use l-infinity by default for testing. Then we can change that just for a few specific tests and ultimately have the l-2 as the default in the final executable.

What do you think?

**Comment by quantumsteve** [comment]
> @quantumsteve when I made the change to the testing and the way the defaults are set, I think it became easy to set a new default, e.g., use l-infinity by default for testing. Then we can change that just for a few specific tests and ultimately have the l-2 as the default in the final executable.
> 
> What do you think?

I'll try switching the default without changing test configurations.

**Comment by quantumsteve** [comment]
@stefan-schnake @mkstoyanov I switched the default

**Review by mkstoyanov — APPROVED** [review]

**Pull request merged**
