### PR TITLE
Add advection_1 PDE

### PR DESCRIPTION
**Pull request by ckendrick**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Adds the 1D advection PDE example implemented during the meeting today. This PDE can be run using `./asgard -p advection_1`.

The MATLAB plotting interface can optionally be used to visualize the PDE:
- Compile ASGarD with the CMake option `-DASGARD_USE_MATLAB=ON`
- Start MATLAB and run `matlab.engine.shareEngine` in the command window.
- Run ASGaRD: `./asgard -p advection_1` and a plot window should appear.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Review by mkstoyanov — APPROVED** [review]

**Comment by mkstoyanov** [comment]
Somewhat related question, are we using 2 or 4 spaces to indent the code? I prefer 4 on a modern monitor, but most of the code is set for 2. We don't enforce it in clang, but this file has inconsistencies.

Perhaps we can start to slowly migrate to 4 spaces throughout.

**Comment by quantumsteve** [comment]
> Somewhat related question, are we using 2 or 4 spaces to indent the code? I prefer 4 on a modern monitor, but most of the code is set for 2. We don't enforce it in clang, but this file has inconsistencies.
> 
> Perhaps we can start to slowly migrate to 4 spaces throughout.

4 spaces is my preference. Add it to the .`clangformat` file?

**Comment by mkstoyanov** [comment]
> > Somewhat related question, are we using 2 or 4 spaces to indent the code? I prefer 4 on a modern monitor, but most of the code is set for 2. We don't enforce it in clang, but this file has inconsistencies.
> > Perhaps we can start to slowly migrate to 4 spaces throughout.
> 
> 4 spaces is my preference. Add it to the .`clangformat` file?

Oh, please `NO` This will break the formatting of every file. :)

We can just move on with 4 spaces for the future and eventually the code will be adjusted. Otherwise, we will have to reformat the entire repo.

**Comment by ckendrick** [comment]
@mkstoyanov @quantumsteve I think we are currently enforcing 2 spaces in clang-format at https://github.com/project-asgard/asgard/blob/a543e0dc1125f357dc8740135837a270afc5cdcd/.clang-format#L73 

The inconsistencies seen in this file might be caused by the line continuation being at 4 spaces: https://github.com/project-asgard/asgard/blob/a543e0dc1125f357dc8740135837a270afc5cdcd/.clang-format#L52

**Comment by mkstoyanov** [comment]
Yes, we are enforcing 2 spaces. Would be nice to change, but only if we can do it without updating the entire code.

**Comment by mkstoyanov** [comment]
Has nothing to do with the PR anyway, we can go ahead and merge.

**Comment by quantumsteve** [comment]
@ckendrick Would you please fix the "This branch is out-of-date with the base branch" warning.

**Pull request merged**
