### PR TITLE
Speed up build and testing and clean up build system.

### PR DESCRIPTION
**Pull request by cianciosa**
Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Review by quantumsteve — APPROVED** [review]
PCH worked well on my Linux workstation. Let's add -DASGARD_USE_PCH=ON to one or more of the AWS builds.

**Review by ckendrick — APPROVED** [review]

**Comment by quantumsteve** [comment]
@cianciosa Would you resolve conflicts so we can get this in?

I would like to get the clang `-Wdtor-name` workaround into develop.

**Comment by cianciosa** [comment]
> @cianciosa Would you resolve conflicts so we can get this in?
> 
> I would like to get the clang `-Wdtor-name` workaround into develop.

It looks like a AWS change is causing the clang tests to fail now. Also there is a change in Kronmult that should probably be merged first so that I can point the Kronmult subproject back to main repo.

**Comment by quantumsteve** [comment]
> It looks like a AWS change is causing the clang tests to fail now. Also there is a change in Kronmult that should probably be merged first so that I can point the Kronmult subproject back to main repo.

I moved `asgard-warnings-clang` to also use `clang++-12`. Should be enabled in the next commit.

**Comment by cianciosa** [comment]
I added that switch option because some of the AWS builds were failing with the PCH. I think it was caused by an issue with the parallel make. Multiple targets would try to generate the PCH file at the same time.

On May 27, 2022, at 6:01 PM, Steven Hahn ***@***.******@***.***>> wrote:



@quantumsteve approved this pull request.

PCH worked well on my Linux workstation. Let's add -DASGARD_USE_PCH=ON to one or more of the AWS builds.

**Pull request merged**
